os: linux
dist: focal
group: stable
language: python
env: 
  - COSIGN_EXPERIMENTAL=1
services:
  - docker
jobs:
  include:
    - stage: "sleep 109"
      script:
        - docker login -u "travisarchitectenterprise" -p "${DOCKER_HUB_PASSWORD}"
        - docker build -t hello-world-python .
        - docker tag hello-world-python travisarchitectenterprise/python-hello-world
        - docker push travisarchitectenterprise/python-hello-world
        - export COSIGN_PASSWORD="${COS_PASSWORD}"
        - cosign sign --key cosign.key travisarchitectenterprise/python-hello-world
       # - yes | cosign sign --key cosign.key arthanaharidas/python-hello-world
        - cosign verify --key cosign.pub travisarchitectenterprise/python-hello-world
        - docker logout
 
keys:
  - Key
