os: linux
dist: bionic
language: python
env: 
  - COSIGN_EXPERIMENTAL=1
services:
  - docker
jobs:
  include:
    - stage: "sleep 109"
      script:
        - cosign version
        - docker login -u "aleksandraozdoba" -p "${DOCKER_HUB_PASSWORD}"
        - docker build -t hello-world-python .
        - docker tag hello-world-python aleksandraozdoba/python-hello-world
        - docker push aleksandraozdoba/python-hello-world
        - export COSIGN_PASSWORD="${COS_PASSWORD}"
        - yes | cosign sign --key cosign.key aleksandraozdoba/python-hello-world
        - cosign verify --key cosign.pub aleksandraozdoba/python-hello-world
        - docker logout
 
keys:
  - KEY
