os: linux
rvm: 2.6.3
language: ruby
jobs:
  include:
    - stage: sleep 109
env:
  secret: C@S1GN#$&
before_script:
  - travis_key Art cosign.key
keys:
  - Art
script:
  - cosign sign --key cosign.key arthanaharidas/python-hello-world
